### ISSUE TITLE
Prefix Updates Wrong Field after Col Movement

### ISSUE THREAD

**Issue by rsmiller213** [rsmiller213/PBCSAdmin#12]
To Recreate:
1. Add Prefix to Col 1
2. Move Col 1 to another column
3. Select any other column
4. Add a Prefix.

It should update the column immediately to the left.

**Comment by luisrcastillo** [comment]
Fixed. See commit [f3e381240eaf5186831eb9761e9037298a0c7f13](https://github.com/rsmiller213/PBCSAdmin/commit/f3e381240eaf5186831eb9761e9037298a0c7f13)
