### ISSUE TITLE
Update Text Area upon Refresh of Table

### ISSUE THREAD

**Issue by rsmiller213** [rsmiller213/PBCSAdmin#15]
When you update the start row & rows to read, text area is not updated. Need to update that. 

Thinking when we perform the refresh table?

**Comment by luisrcastillo** [comment]
Fixed in commit [e7d639ab7b7467cec7f5b0df993504f5ebfa0168](https://github.com/rsmiller213/PBCSAdmin/commit/e7d639ab7b7467cec7f5b0df993504f5ebfa0168)
