### ISSUE TITLE
Column Actions

### ISSUE THREAD

**Issue by rsmiller213** [rsmiller213/PBCSAdmin#18]
Move
Split
Join
Create Using Join
Create Using Text

Need to track column movements via a table. 

| Operation | Moved From | Moved To | Characters |
| --- | --- | --- | --- |
| Add Column | Null | Last Col Idx | Null |
| Split (Delim) | Col Split Idx | Last Col Idx | Delim |
| Split (# Chars) | Col Split Idx | Last Col Idx | # of Chars |
| Create with Join | Left Col " " Right Col | Last Col Idx | Delim |
| Move | From Idx | To Idx | Null |

Refer to #17 for Merge Join

**Comment by rsmiller213** [comment]
For inspiration!

![image](https://cloud.githubusercontent.com/assets/19271148/15261927/39be3df6-192d-11e6-97e8-69dff6725637.png)

**Comment by luisrcastillo** [comment]
Complete and fully functional
