### ISSUE TITLE
Start Row

### ISSUE THREAD

**Issue by rsmiller213** [rsmiller213/PBCSAdmin#2]
Data Source Properties Pane
Allows them to choose the row to start displaying. I.e. i could say display 500 rows starting at row 40,000. Allows them to see different possibilities in the file

**Comment by luisrcastillo** [comment]
Done. See commit [33ae33bb0af7a06445a63eb881f588ad2a378ae0](https://github.com/rsmiller213/PBCSAdmin/commit/33ae33bb0af7a06445a63eb881f588ad2a378ae0). A new version of the getModelFromCsvFile was created to accomodate this. This needs to be tested more. Also, more conditions and perhaps error trapping should be added in the btnRefreshActionPerformed. Perhaps something Master @rsmiller213 can look into

**Comment by rsmiller213** [comment]
ill look this evening

**Comment by luisrcastillo** [comment]
@rsmiller213 do you think we can close this?

**Comment by rsmiller213** [comment]
i still need to add portion that will update the TextArea after you modify this. Other than that it is working.

**Comment by rsmiller213** [comment]
Closing. Opening a new bug for updating TextArea
