### ISSUE TITLE
JTable - Prefix Disappears when you select the column

### ISSUE THREAD

**Issue by rsmiller213** [rsmiller213/PBCSAdmin#20]
Happens with all the column properties, even data field. Column header stays though. 

To recreate:
1. Click on a column
2. Name the column & Put a prefix
   2a. I notice when you hit update field it deselects your column
3. Re-select the column and no prefix. 

Before:
![image](https://cloud.githubusercontent.com/assets/19271148/15369996/f255770c-1d02-11e6-84c0-60bbfcbf7e5e.png)

After:
![image](https://cloud.githubusercontent.com/assets/19271148/15370004/0272b852-1d03-11e6-8599-3c0dfbb1ec42.png)

**Comment by luisrcastillo** [comment]
Fixed. See commit [08e21a55476a06fdcd227861412084a39bbe6dc0](https://github.com/rsmiller213/PBCSAdmin/commit/08e21a55476a06fdcd227861412084a39bbe6dc0)
