### ISSUE TITLE
Find/Replace Table

### ISSUE THREAD

**Issue by rsmiller213** [rsmiller213/PBCSAdmin#5]
Need to build the Find/Replace functionality a little better

I think the best course of action would be a "Find/Replace" button that will launch a table in another window, they can then specify. This might be functionality that is moved to the next phase when we start allowing them to store their modifications as a config file. 
- Find What
- Replace With
- Match Case (Check Box)
- Match Full Word (Check Box)

**Comment by luisrcastillo** [comment]
Do I smell a mapping table?

**Comment by rsmiller213** [comment]
So that is the ultimate idea. 

I think we can take it in steps though.

**Comment by rsmiller213** [comment]
Added a JDialog to show the table & options

Need to store by column, all table rows related to that column (Replace, With, Match Whole Word, Match Case). 

If column header is updated we need to update the stored information to reflect that.

**Comment by luisrcastillo** [comment]
Complete and fully functional
