### ISSUE TITLE
Load Profiles

### ISSUE THREAD

**Issue by rsmiller213** [rsmiller213/PBCSAdmin#6]
Allow users to save off their work in a config/rule file that we can then re-use, open, edit etc and it can be used for command line actions

**Comment by luisrcastillo** [comment]
No drag and drop after all :( We'll setup an option for a move
Track splits, joins, new columns, etc
Column Headers, find, replace, prefix, suffix, data check

**Comment by luisrcastillo** [comment]
Complete and fully functional
