### ISSUE TITLE
Output File

### ISSUE THREAD

**Issue by rsmiller213** [rsmiller213/PBCSAdmin#7]
We need to write the output to a text file

Attached are the before & after that we are trying to replicate.
Note on the AfterTransform we have a header row that **only** relates to the data columns

[AfterTransform.txt](https://github.com/rsmiller213/PBCSAdmin/files/257735/AfterTransform.txt)
[BeforeTransform.txt](https://github.com/rsmiller213/PBCSAdmin/files/257736/BeforeTransform.txt)

**Comment by luisrcastillo** [comment]
This is now fixed. Export file is working the way we want it to
